/** Typed wrappers around the backend REST endpoints. */
import type {
  AttachmentsListResponse,
  AttachmentRecord,
  CatalogModel,
  ConversationDetail,
  ConversationsListResponse,
  ConversationSummary,
  HealthResponse,
  InstalledModelsResponse,
  LibrarySearchResponse,
  LocationResponse,
  RecommendationsResponse,
  RunCodeResponse,
  TiersResponse,
  UploadResponse,
  VisionCheckResponse,
  WebSearchStatus,
} from '../types/api'
import { apiUrl } from './config'

async function unwrap<T>(response: Response, path: string): Promise<T> {
  if (!response.ok) {
    let detail = `Request failed with status ${response.status}`
    try {
      const payload = await response.json()
      if (payload?.detail) detail = String(payload.detail)
    } catch {
      /* keep the status-based message */
    }
    throw new Error(detail)
  }
  void path
  return (await response.json()) as T
}

async function getJson<T>(path: string): Promise<T> {
  let response: Response
  try {
    response = await fetch(apiUrl(path))
  } catch {
    throw new Error(
      `Cannot reach the backend at ${apiUrl(path)}. Start it with: uvicorn app.main:app --port 8000`,
    )
  }
  return unwrap<T>(response, path)
}

async function sendJson<T>(
  path: string,
  method: 'POST' | 'PATCH' | 'DELETE',
  body?: unknown,
): Promise<T> {
  let response: Response
  try {
    response = await fetch(apiUrl(path), {
      method,
      headers: body === undefined ? undefined : { 'Content-Type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
  } catch {
    throw new Error(`Cannot reach the backend at ${apiUrl(path)}.`)
  }
  return unwrap<T>(response, path)
}

export function getHealth(): Promise<HealthResponse> {
  return getJson<HealthResponse>('/api/health')
}

export function getRecommendations(
  limit = 3,
  refresh = false,
): Promise<RecommendationsResponse> {
  return getJson<RecommendationsResponse>(
    `/api/recommendations?limit=${limit}&refresh=${refresh}`,
  )
}

export function getTiers(refresh = false): Promise<TiersResponse> {
  return getJson<TiersResponse>(`/api/tiers?refresh=${refresh}`)
}

export function getInstalledModels(): Promise<InstalledModelsResponse> {
  return getJson<InstalledModelsResponse>('/api/models/installed')
}

export async function deleteModel(name: string): Promise<void> {
  await sendJson<{ deleted: boolean }>(
    `/api/models/${encodeURIComponent(name)}`,
    'DELETE',
  )
}

export async function preloadModel(model: string): Promise<void> {
  await sendJson<{ ready: boolean }>('/api/models/preload', 'POST', { model })
}

export function searchCatalog(query: string): Promise<CatalogModel[]> {
  return getJson<CatalogModel[]>(`/api/models/search?q=${encodeURIComponent(query)}`)
}

export function searchLibrary(query: string): Promise<LibrarySearchResponse> {
  return getJson<LibrarySearchResponse>(
    `/api/models/library?q=${encodeURIComponent(query)}`,
  )
}

/* ------------------------------- Conversations -------------------------------- */

export async function listConversations(): Promise<ConversationSummary[]> {
  const result = await getJson<ConversationsListResponse>('/api/conversations')
  return result.conversations
}

export function createConversation(): Promise<ConversationSummary> {
  return sendJson<ConversationSummary>('/api/conversations', 'POST', {})
}

export function getConversation(id: string): Promise<ConversationDetail> {
  return getJson<ConversationDetail>(`/api/conversations/${encodeURIComponent(id)}`)
}

export function renameConversation(
  id: string,
  title: string,
): Promise<ConversationSummary> {
  return sendJson<ConversationSummary>(
    `/api/conversations/${encodeURIComponent(id)}`,
    'PATCH',
    { title },
  )
}

export async function deleteConversation(id: string): Promise<void> {
  await sendJson<{ deleted: boolean }>(
    `/api/conversations/${encodeURIComponent(id)}`,
    'DELETE',
  )
}

/* -------------------------------- Attachments -------------------------------- */

/**
 * Upload files to one conversation.
 *
 * Deliberately not routed through sendJson: multipart bodies must NOT carry an
 * explicit Content-Type header, because the boundary token is generated by the
 * browser and setting the header by hand omits it, which makes the request
 * unparseable server-side.
 */
export async function uploadAttachments(
  conversationId: string,
  files: File[],
): Promise<UploadResponse> {
  const form = new FormData()
  for (const file of files) form.append('files', file)

  const path = `/api/attachments/${encodeURIComponent(conversationId)}`
  let response: Response
  try {
    response = await fetch(apiUrl(path), { method: 'POST', body: form })
  } catch {
    throw new Error(`Cannot reach the backend at ${apiUrl(path)}.`)
  }
  return unwrap<UploadResponse>(response, path)
}

export async function listAttachments(
  conversationId: string,
): Promise<AttachmentRecord[]> {
  const result = await getJson<AttachmentsListResponse>(
    `/api/attachments/${encodeURIComponent(conversationId)}`,
  )
  return result.attachments
}

export async function deleteAttachment(attachmentId: string): Promise<void> {
  await sendJson<{ deleted: boolean }>(
    `/api/attachments/${encodeURIComponent(attachmentId)}`,
    'DELETE',
  )
}

/** URL for a stored image, used directly as an <img> src. */
export function attachmentFileUrl(attachmentId: string): string {
  return apiUrl(`/api/attachments/file/${encodeURIComponent(attachmentId)}`)
}

/** Execute a chart script the user approved. Scoped to the conversation's files. */
export function runChartCode(
  code: string,
  conversationId: string | null,
): Promise<RunCodeResponse> {
  return sendJson<RunCodeResponse>('/api/attachments/run-code', 'POST', {
    code,
    conversation_id: conversationId,
  })
}

/* ------------------------------- Capabilities -------------------------------- */

export function checkVision(model: string): Promise<VisionCheckResponse> {
  return getJson<VisionCheckResponse>(
    `/api/capabilities/vision-check?model=${encodeURIComponent(model)}`,
  )
}

/* -------------------------------- Web search --------------------------------- */

export function getWebSearchStatus(refresh = false): Promise<WebSearchStatus> {
  return getJson<WebSearchStatus>(`/api/websearch/status?refresh=${refresh}`)
}

/* ------------------------------- User context -------------------------------- */

/**
 * Both flags default off so opening a panel neither probes the OS nor raises a
 * permission prompt. `precise` asks the OS location service for coordinates,
 * which shows a system consent dialog.
 */
export function getLocation(detect = false, precise = false): Promise<LocationResponse> {
  return getJson<LocationResponse>(
    `/api/context/location?detect=${detect}&precise=${precise}`,
  )
}

export function setLocation(
  city: string,
  region?: string,
  country?: string,
): Promise<LocationResponse> {
  return sendJson<LocationResponse>('/api/context/location', 'POST', {
    city,
    region: region || null,
    country: country || null,
  })
}

export function clearLocation(): Promise<LocationResponse> {
  return sendJson<LocationResponse>('/api/context/location', 'DELETE')
}
